name: material_stepper
description: A new Flutter package project.
homepage: https://github.com/TahaTesser
repository: https://github.com/TahaTesser/material_stepper
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
